/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppVeilleRouteImport } from './routes/app/veille'
import { Route as AppTarifsRouteImport } from './routes/app/tarifs'
import { Route as AppRelancesRouteImport } from './routes/app/relances'
import { Route as AppPropositionsRouteImport } from './routes/app/propositions'
import { Route as AppPipelineRouteImport } from './routes/app/pipeline'
import { Route as AppParametresRouteImport } from './routes/app/parametres'
import { Route as AppOpportunitesRouteImport } from './routes/app/opportunites'
import { Route as AppEntreprisesRouteImport } from './routes/app/entreprises'
import { Route as AppDocumentsRouteImport } from './routes/app/documents'
import { Route as AppCopilotRouteImport } from './routes/app/copilot'
import { Route as AppPropositionsIdRouteImport } from './routes/app/propositions.$id'
import { Route as AppOpportunitesIdRouteImport } from './routes/app/opportunites.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVeilleRoute = AppVeilleRouteImport.update({
  id: '/veille',
  path: '/veille',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTarifsRoute = AppTarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRelancesRoute = AppRelancesRouteImport.update({
  id: '/relances',
  path: '/relances',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPropositionsRoute = AppPropositionsRouteImport.update({
  id: '/propositions',
  path: '/propositions',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppParametresRoute = AppParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOpportunitesRoute = AppOpportunitesRouteImport.update({
  id: '/opportunites',
  path: '/opportunites',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEntreprisesRoute = AppEntreprisesRouteImport.update({
  id: '/entreprises',
  path: '/entreprises',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCopilotRoute = AppCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPropositionsIdRoute = AppPropositionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPropositionsRoute,
} as any)
const AppOpportunitesIdRoute = AppOpportunitesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppOpportunitesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/entreprises': typeof AppEntreprisesRoute
  '/app/opportunites': typeof AppOpportunitesRouteWithChildren
  '/app/parametres': typeof AppParametresRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/propositions': typeof AppPropositionsRouteWithChildren
  '/app/relances': typeof AppRelancesRoute
  '/app/tarifs': typeof AppTarifsRoute
  '/app/veille': typeof AppVeilleRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/opportunites/$id': typeof AppOpportunitesIdRoute
  '/app/propositions/$id': typeof AppPropositionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/entreprises': typeof AppEntreprisesRoute
  '/app/opportunites': typeof AppOpportunitesRouteWithChildren
  '/app/parametres': typeof AppParametresRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/propositions': typeof AppPropositionsRouteWithChildren
  '/app/relances': typeof AppRelancesRoute
  '/app/tarifs': typeof AppTarifsRoute
  '/app/veille': typeof AppVeilleRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/opportunites/$id': typeof AppOpportunitesIdRoute
  '/app/propositions/$id': typeof AppPropositionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/entreprises': typeof AppEntreprisesRoute
  '/app/opportunites': typeof AppOpportunitesRouteWithChildren
  '/app/parametres': typeof AppParametresRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/propositions': typeof AppPropositionsRouteWithChildren
  '/app/relances': typeof AppRelancesRoute
  '/app/tarifs': typeof AppTarifsRoute
  '/app/veille': typeof AppVeilleRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/opportunites/$id': typeof AppOpportunitesIdRoute
  '/app/propositions/$id': typeof AppPropositionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/connexion'
    | '/inscription'
    | '/app/copilot'
    | '/app/documents'
    | '/app/entreprises'
    | '/app/opportunites'
    | '/app/parametres'
    | '/app/pipeline'
    | '/app/propositions'
    | '/app/relances'
    | '/app/tarifs'
    | '/app/veille'
    | '/app/'
    | '/api/auth/$'
    | '/app/opportunites/$id'
    | '/app/propositions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connexion'
    | '/inscription'
    | '/app/copilot'
    | '/app/documents'
    | '/app/entreprises'
    | '/app/opportunites'
    | '/app/parametres'
    | '/app/pipeline'
    | '/app/propositions'
    | '/app/relances'
    | '/app/tarifs'
    | '/app/veille'
    | '/app'
    | '/api/auth/$'
    | '/app/opportunites/$id'
    | '/app/propositions/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/connexion'
    | '/inscription'
    | '/app/copilot'
    | '/app/documents'
    | '/app/entreprises'
    | '/app/opportunites'
    | '/app/parametres'
    | '/app/pipeline'
    | '/app/propositions'
    | '/app/relances'
    | '/app/tarifs'
    | '/app/veille'
    | '/app/'
    | '/api/auth/$'
    | '/app/opportunites/$id'
    | '/app/propositions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ConnexionRoute: typeof ConnexionRoute
  InscriptionRoute: typeof InscriptionRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/veille': {
      id: '/app/veille'
      path: '/veille'
      fullPath: '/app/veille'
      preLoaderRoute: typeof AppVeilleRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/tarifs': {
      id: '/app/tarifs'
      path: '/tarifs'
      fullPath: '/app/tarifs'
      preLoaderRoute: typeof AppTarifsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/relances': {
      id: '/app/relances'
      path: '/relances'
      fullPath: '/app/relances'
      preLoaderRoute: typeof AppRelancesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/propositions': {
      id: '/app/propositions'
      path: '/propositions'
      fullPath: '/app/propositions'
      preLoaderRoute: typeof AppPropositionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/pipeline': {
      id: '/app/pipeline'
      path: '/pipeline'
      fullPath: '/app/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/parametres': {
      id: '/app/parametres'
      path: '/parametres'
      fullPath: '/app/parametres'
      preLoaderRoute: typeof AppParametresRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/opportunites': {
      id: '/app/opportunites'
      path: '/opportunites'
      fullPath: '/app/opportunites'
      preLoaderRoute: typeof AppOpportunitesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/entreprises': {
      id: '/app/entreprises'
      path: '/entreprises'
      fullPath: '/app/entreprises'
      preLoaderRoute: typeof AppEntreprisesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/copilot': {
      id: '/app/copilot'
      path: '/copilot'
      fullPath: '/app/copilot'
      preLoaderRoute: typeof AppCopilotRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/propositions/$id': {
      id: '/app/propositions/$id'
      path: '/$id'
      fullPath: '/app/propositions/$id'
      preLoaderRoute: typeof AppPropositionsIdRouteImport
      parentRoute: typeof AppPropositionsRoute
    }
    '/app/opportunites/$id': {
      id: '/app/opportunites/$id'
      path: '/$id'
      fullPath: '/app/opportunites/$id'
      preLoaderRoute: typeof AppOpportunitesIdRouteImport
      parentRoute: typeof AppOpportunitesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppOpportunitesRouteChildren {
  AppOpportunitesIdRoute: typeof AppOpportunitesIdRoute
}

const AppOpportunitesRouteChildren: AppOpportunitesRouteChildren = {
  AppOpportunitesIdRoute: AppOpportunitesIdRoute,
}

const AppOpportunitesRouteWithChildren = AppOpportunitesRoute._addFileChildren(
  AppOpportunitesRouteChildren,
)

interface AppPropositionsRouteChildren {
  AppPropositionsIdRoute: typeof AppPropositionsIdRoute
}

const AppPropositionsRouteChildren: AppPropositionsRouteChildren = {
  AppPropositionsIdRoute: AppPropositionsIdRoute,
}

const AppPropositionsRouteWithChildren = AppPropositionsRoute._addFileChildren(
  AppPropositionsRouteChildren,
)

interface AppRouteRouteChildren {
  AppCopilotRoute: typeof AppCopilotRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppEntreprisesRoute: typeof AppEntreprisesRoute
  AppOpportunitesRoute: typeof AppOpportunitesRouteWithChildren
  AppParametresRoute: typeof AppParametresRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppPropositionsRoute: typeof AppPropositionsRouteWithChildren
  AppRelancesRoute: typeof AppRelancesRoute
  AppTarifsRoute: typeof AppTarifsRoute
  AppVeilleRoute: typeof AppVeilleRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppCopilotRoute: AppCopilotRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppEntreprisesRoute: AppEntreprisesRoute,
  AppOpportunitesRoute: AppOpportunitesRouteWithChildren,
  AppParametresRoute: AppParametresRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppPropositionsRoute: AppPropositionsRouteWithChildren,
  AppRelancesRoute: AppRelancesRoute,
  AppTarifsRoute: AppTarifsRoute,
  AppVeilleRoute: AppVeilleRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  ConnexionRoute: ConnexionRoute,
  InscriptionRoute: InscriptionRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
